### PR TITLE
refactor: dev tools install script

### PR DESCRIPTION
**Pull request by jthegedus**
- [x] fix some devtools script bugs
- [x] update docs
- [x] simplify `asdf` tool installation with function. program the happy path for now.
- [x] install asdf plugins from a config file

### CODE REVIEW

**Comment by christippett** [comment]
Hey, what do you think of prompting the user for what asdf plugins they want installed at the beginning of the script. If 'y' install, if 'n' skip.

**Comment by jthegedus** [comment]
As I am writing this I am think of doing something like this

https://github.com/jthegedus/asdf-gcloud/blob/master/lib/dependencies.txt

Where there's a config people can configure and the default will be my setup.

**Comment by christippett** [comment]
Love it!

**Comment by jthegedus** [comment]
I'm just setting up my Ubuntu 20.04 machine and running these scripts and finding a bunch of issues. I wrote them while I was manually doing my last setup so hadn't executed them all through :sweat_smile:

**Comment by jthegedus** [comment]
I'll be finishing this up tomorrow but it is almost done. Will make the configurable asdf plugins tomorrow in another PR

**Comment by jthegedus** [comment]
@christippett I renamed the `config/` to `dotfiles/` which might affect some of your own scripts.

The devtools setup is now just `asdf`, `asdf-plugins` from a config file, and some "extras" which I may move to above the `asdf` installation

**Comment by jthegedus** [comment]
What an installation of the default `asdf` plugins looks like on re-run:

Screenshot from 2020-04-10 17-45-51

**Pull request merged**
